### ISSUE TITLE
IndexError when writing to hippo pickle

### ISSUE THREAD

**Issue by kate-fie** [kate-fie/syndirella#63]
First example:
```
        Syndirella 👑 will elaborate the following route for NC(=O)N1CCN(C(=O)c2ccco2)C[C@H]1NC(=O)c1cscn1 | IBNRYRKGRKRSMK-UHFFFAOYSA-N:
        Route UUID: Mf6ii6
        Reaction Names: ['Amidation', 'Nucleophilic_substitution_with_amine', 'N-Bn_deprotection', 'Amide_Schotten-Baumann_with_amine']
        Number of Steps: 4

...

2024-09-19 01:04:50,834 - syndirella.slipper.SlipperFitter - INFO - 9117 (93.71%) successful placements where ∆∆G < 0 and RMSD < 2 Å and passed intramolecular geometry checks.
2024-09-19 01:04:54,109 - syndirella.pipeline - CRITICAL - Error elaborating compound NC(=O)N1CCN(C(=O)c2ccco2)C[C@H]1NC(=O)c1cscn1. Traceback (most recent call last):
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/pipeline.py", line 87, in elaborate_from_cobbler_workshops
    slipper.write_products_to_hippo()  # only write at the end after placement, to get correct route_uuid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 131, in write_products_to_hippo
    hippo_df = self._structure_products_for_hippo(placements_df=placements,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 180, in _structure_products_for_hippo
    hippo_df_step: pd.DataFrame = self._structure_step_for_hippo(step, products_df)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 252, in _structure_step_for_hippo
    reaction: str = products_df['reaction'].iloc[0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

Second example:
```
        Syndirella 👑 will elaborate the following route for CN(C)C(=O)Cn1nc(CNc2ccc(O)cc2)c2ccccc21 | WLFMTZKZYACXSW-UHFFFAOYSA-N:
        Route UUID: 7WG6rn
        Reaction Names: ['Amidation', 'Reductive_amination']
        Number of Steps: 2

2024-09-18 18:26:49,121 - syndirella.slipper.SlipperFitter - INFO - 3 (42.86%) successful placements where ∆∆G < 0 and RMSD < 2 Å and passed intramolecular geometry checks.
2024-09-18 18:26:49,171 - syndirella.pipeline - CRITICAL - Error elaborating compound CN(C)C(=O)Cn1nc(CNc2ccc(O)cc2)c2ccccc21. Traceback (most recent call last):
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/pipeline.py", line 87, in elaborate_from_cobbler_workshops
    slipper.write_products_to_hippo()  # only write at the end after placement, to get correct route_uuid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 131, in write_products_to_hippo
    hippo_df = self._structure_products_for_hippo(placements_df=placements,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 180, in _structure_products_for_hippo
    hippo_df_step: pd.DataFrame = self._structure_step_for_hippo(step, products_df)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/syndirella/syndirella/slipper/Slipper.py", line 252, in _structure_step_for_hippo
    reaction: str = products_df['reaction'].iloc[0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/xchem-fragalysis-2/kfieseler/conda/envs/syndirella/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by kate-fie** [comment]
Fixed. Trying to filter dataframe on non-existent column.
